version: "3.8"
services:
  springbootapp:
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
      - redis
    restart: on-failure:2

  mysqldb:
    image: mysql:8
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db_caching
      MYSQL_ROOT_PASSWORD: root

  rediscache:
    image: redis:7-alpine
    # hostname: redis
    ports:
      - "6379:6379"
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

volumes:
  db-data: